### ISSUE TITLE
Installation issues from source (R 3.5.1)

### ISSUE THREAD

**Issue by manolo20** [grahamjwhite/IndexNumR#11]
Hi,

Thanks for your package which I was able to install it from CRAN.

Although, I just wanted to point out that when I tried installing your package from your repo I got the following error:
```
> devtools::install_github("grahamjwhite/IndexNumR")  
Installation failed: Timeout was reached: Connection timed out after 10000 milliseconds
```

**Comment by grahamjwhite** [comment]
Hi Manolo,

It looks like this issue crops up from time to time when using Devtools. It could be a number of things but it looks like you're having trouble connecting to GitHub. That could be caused by a firewall or proxy server for example. One workaround is to download the zip file of the package and then install it from there. To do that

- go to the GitHub code page for IndexNumR (click the '<>Code' tab above)
- click the green 'Clone or Download' button near the top right
- unzip the downloaded zip file
- in RStudio, use devtools::install("path to package folder")

In Windows it might look something like:
devtools::install("C://Users/username/download/IndexNumR-master/IndexNumR-master")

Another option is to try using a different internet connection. For example, if you're using a University, corporate, or public wifi then try using your home internet connection. 

Let me know if you're still having problems.

Cheers, 
Graham
